spring.datasource.url=jdbc:h2:mem:gamestarsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console web do H2 para você visualizar as tabelas no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'update' cria as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
# Exibe as queries SQL que o Spring gera no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true